/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.zawiejamobile.kotlin_fun

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
